#ifndef P1_XESTIONERROS_H
#define P1_XESTIONERROS_H


#define FICHEIRO_NON_ATOPADO 1
#define LEXEMA_DESCONOCIDO 2
#define LEXEMA_TAM_EXCEDIDO 3
#define COMENTARIO_MULTILINEA_NON_PECHADO 4
#define STRING_NON_PECHADO 5
#define BYTE_OCT_POUCOS_DIXITOS 6
#define BYTE_HEX_POUCOS_DIXITOS 7
#define UNICODE_PEQUENO_INVALIDO 8
#define UNICODE_GRANDE_INVALIDO 9
#define CARACTER_ESCAPADO_SECUENCIA_DESCONOCIDA 10
#define INT_MAL_FORMADO 11
#define FLOAT_HEX_MAL_FORMADO 12
#define FLOAT_EXPO_MAL_FORMADO 13
#define IMAGINARY_MAL_FORMADO 14
#define RUNA_NON_PECHADA 15
#define RUNA_MOITOS_CARACTERES 16


void lanzarErro(int codigo);


#endif
