#ifndef P1_XESTIONERROS_H
#define P1_XESTIONERROS_H


#define FICHEIRO_NON_ATOPADO 1
#define LEXEMA_TAM_EXCEDIDO 2
#define COMENTARIO_MULTILINEA_NON_PECHADO 3
#define STRING_CRUDO_NON_PECHADO 4
#define STRING_INTERPRETADO_NON_PECHADO 5
#define BYTE_OCT_POUCOS_DIXITOS 6
#define BYTE_HEX_POUCOS_DIXITOS 7
#define UNICODE_PEQUENO_INVALIDO 8
#define UNICODE_GRANDE_INVALIDO 9
#define CARACTER_ESCAPADO_SECUENCIA_DESCONOCIDA 10


void lanzarErro(int codigo);


#endif
